version: 2

sources:
  - name: raw
    description: the dataset for greenwez's valuable data
    schema: gz_raw_data
    tables:
    
      - name: adwords
        description: adwords campaign for greenweez
        identifier: raw_gz_adwords
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness:
          warn_after: { count: 90, period: day }
        tests:
          - unique:
              column_name: "(date_date || '-' || campaign_key)"
        columns:
          - name: date_date
            description: date of the campaign, PK
          - name: paid_source
            description: name of the campaign source
          - name: campaign_key
            description: campaign ID number, PK
          - name: camPGN_name
            description: campaign name
          - name: ads_cost
            description: cost of the campaign
          - name: impression
            description: number of impressions
          - name: click
            description: number of clicks

      - name: bing
        description: bing campaign for greenweez
        identifier: raw_gz_bing
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness:
          warn_after: { count: 90, period: day }
        tests:
          - unique:
              column_name: "(date_date || '-' || campaign_key)"
        columns:
          - name: date_date
            description: date of the campaign, PK
          - name: paid_source
            description: name of the campaign source
          - name: campaign_key
            description: campaign ID number, PK
          - name: camPGN_name
            description: campaign name
          - name: ads_cost
            description: cost of the campaign
          - name: impression
            description: number of impressions
          - name: click
            description: number of clicks

      - name: criteo
        description: criteo campaign for greenweez
        identifier: raw_gz_criteo
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness:
          warn_after: { count: 90, period: day }
        tests:
          - unique:
              column_name: "(date_date || '-' || campaign_key)"
        columns:
          - name: date_date
            description: date of the campaign, PK
          - name: paid_source
            description: name of the campaign source
          - name: campaign_key
            description: campaign ID number, PK
          - name: campaign_name
            description: camPGN_name
          - name: ads_cost
            description: cost of the campaign
          - name: impression
            description: number of impressions
          - name: click
            description: number of clicks

      - name: facebook
        description: facebook campaign for greenweez
        identifier: raw_gz_facebook
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness:
          warn_after: { count: 90, period: day }
        tests:
          - unique:
              column_name: "(date_date || '-' || campaign_key)"
        columns:
          - name: date_date
            description: date of the campaign, PK
          - name: paid_source
            description: name of the campaign source
          - name: campaign_key
            description: campaign ID number, PK
          - name: campaign_name
            description: camPGN_name
          - name: ads_cost
            description: cost of the campaign
          - name: impression
            description: number of impressions
          - name: click
            description: number of clicks

      - name: sales
        description: sales data for greenweez
        identifier: raw_gz_sales
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness:
          warn_after: { count: 90, period: day }
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
        columns:
          - name: date_date
            description: the date of order
          - name: orders_id
            description: together with product_id constitutes the primary key
          - name: pdt_id
            description: together with orders_id constitutes the primary key
          - name: revenue
            description: the turnover generated by the product
          - name: quantity
            description: the quantity ordered
            
      - name: product
        description: product data for greenweez
        identifier: raw_gz_product
        columns:
          - name: products_id
            description: the primary key of the product table
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: the purchase price of the product
            
      - name: ship
        description: shipment data for greenweez
        identifier: raw_gz_ship
        columns:
          - name: orders_id
            description: the primary key of the shipment table
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: the revenue generated by the order shipped
          - name: logcost
            description: the logistic cost of the shipment, shipping_fee minus logcost minus ship_cost will give the marginal cost
          - name: ship_cost
            description: the shipment cost of the shipment, shipping_fee minus logcost minus ship_cost will give the marginal cost

models:
  - name: models/intermediate/int_sales_margin.sql
    description: sales margin calculation
    tests:
      - unique:
          column_name: "(orders_id || '-' || date_date)"
      - not_null:
          column_name: "(orders_id || '-' || date_date)"
    columns:
      - name: orders_id
        description: Order ID
      - name: date_date
        description: the date of order
      - name: revenue
        description: the turnover generated by the order
      - name: quantity
        description: the quantity sold
      - name: purchase_cost
        description: the purchse cost of the order
      - name: margin
        description: the margin by order

  - name: models/intermediate/int_orders_margin.sql
    description: orders margin calculation
    columns:
      - name: orders_id
        description: Order ID
        tests:
          - unique
          - not_null
      - name: date_date
        description: date of the order
      - name: revenue
        description: the turnover generated by the order
      - name: quantity
        description: the quantity sold
      - name: purchase_cost
        description: the purchse cost of the order
      - name: margin
        description: the margin by product

  - name: models/intermediate/int_orders_operational.sql
    description: operational margin calculation
    columns:
      - name: orders_id
        description: Order ID
        tests:
          - unique
          - not_null
      - name: date_date
        description: date of the order
      - name: operational_margin
        description: the operational margin by product
      - name: quantity
        description: the quantity sold
      - name: revenue
        description: the turnover generated by the order
      - name: purchase_cost
        description: the purchse cost of the order
      - name: shipping_fee
        description: the revenue generated by the order shipped
      - name: logcost
        description: the logistic cost of the shipment

  - name: models/mart/finance/finance_days.sql
    description: financial KPIs calculated on a daily basis
    columns:
      - name: date_date
        description: the date of order
        tests:
          - unique
          - not_null
      - name: total_transactions
        description: the total transcation number on a daily basis
      - name: revenue
        description: the total turnover on a daily basis
      - name: average_basket
        description: the average basket on a daily basis
      - name: operational_margin
        description: the total operational margin on a daily basis
      - name: purchase_cost
        description: the total purchase cost on a daily basis
      - name: log_costs
        description: the total logistic cost on a daily basis
      - name: shipping_fee
        description: the total shipping fee paid by the customers on a daily basis
      - name: products_sold
        description: the total number of products sold on a daily basis